apiVersion: v1
kind: Service
metadata:
  name: tintor-matching-service
spec:
  selector:
    app: tintor-matching
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888 
      nodePort: 30100
  type: NodePort