apiVersion: v1
kind: Service
metadata:
  name: tintor-fe-service
spec:
  selector:
    app: tintor-fe
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30200
  type: NodePort