apiVersion: v1
kind: Service
metadata:
  name: tintor-be-service
spec:
  selector:
    app: tintor-be
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30300
  type: NodePort
