apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tintor-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:dat-doan-tpv-clv/tintor.git
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tintor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true