name: tintor-fe-workflow

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug secret values
        run: |
          echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Token exists: ${{ secrets.DOCKERHUB_TOKEN != '' }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: tintor-fe
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tintor-fe:${{ github.sha }}
          platforms: linux/amd64

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout tintor-config repo
        uses: actions/checkout@v4
        with:
          repository: dat-doan-tpv-clv/tintor-config
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          version: v5.0.0

      - name: Update image tag in kustomization.yaml
        run: |
          cd overlays/production/fe
          kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/tintor-fe:${{ github.sha }}
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add kustomization.yaml
          git commit -m "chore: update image tag to ${{ github.sha }}"
          git pull --rebase origin master
          git push
