apiVersion: apps/v1
kind: Deployment
metadata:
  name: tintor-fe
  namespace: tintor-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tintor-fe
  template:
    metadata: 
      name: tintor-fe
      labels:
        app: tintor-fe
    spec:
      containers: 
        - name: tintor-fe
          image: doandat8888/tintor-fe:latest
          env:
            - name: VITE_FIREBASE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: tintor-fe-env
                  key: VITE_FIREBASE_API_KEY
            - name: VITE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: tintor-fe-env
                  key: VITE_AUTH_DOMAIN
            - name: VITE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: tintor-fe-env
                  key: VITE_PROJECT_ID
            - name: VITE_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: tintor-fe-env
                  key: VITE_STORAGE_BUCKET
            - name: VITE_MESSAGING_SENDER_ID
              valueFrom:
                configMapKeyRef:
                  name: tintor-fe-env
                  key: VITE_MESSAGING_SENDER_ID
            - name: VITE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: tintor-fe-env
                  key: VITE_APP_ID
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: tintor-fe-env
                  key: VITE_API_URL
          ports:
          - containerPort: 5173
            protocol: TCP
