apiVersion: v1
kind: Service
metadata:
  name: tintor-matching-service
  namespace: tintor-matching
  labels:
    app: tintor-matching
spec:
  selector:
    app: tintor-matching
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888 
      nodePort: 30100
  type: NodePort