apiVersion: v1
kind: Service
metadata:
  name: tintor-be-service
  namespace: tintor-be
  labels:
    app: tintor-be
spec:
  type: NodePort
  selector:
    app: tintor-be
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30300